version: '3.9'
services:
  local_iot_db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=iot
      - POSTGRES_PASSWORD=iot
      - POSTGRES_DB=iot
      - DATABASE_HOST=postgres
    ports:
      - '35432:5432'
    networks:
      iotnet:
        ipv4_address: 192.168.92.21
    #   - ./qa_pg-data:/var/lib/postgresql/data
  local_iot_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6001:6001'
    networks:
      iotnet:
        ipv4_address: 192.168.92.22
    depends_on:
      - db
################
networks:
  iotnet:
    driver: bridge #allows for container to talk to each other
    ipam:
      config:
        - subnet: '192.168.92.0/24'
